package com.nti.nti_backend.email;

public enum EmailTemplateType {
    VERIFICATION,
    RESET_PASSWORD,
    WELCOME,
    APPLICATION_STATUS_CHANGED,
    NEW_USER_NOTIFICATION,
    MENTOR_INVITE,
    ORG_MEMBER_INVITE,
    ACCOUNT_APPROVED,
    ACCOUNT_REJECTED,
    ACCOUNT_SUSPENDED,
    MENTOR_ASSIGNED,
    DEADLINE_REMINDER,
    PROJECT_CLOSED
}
