# ??? ???? ????? ???????????????????????????????????????????????????
spring.datasource.url=jdbc:postgresql://localhost:5432/nti_db
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ??? Email (Mailtrap ??? ????????) ????????????????????????????????
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=b526e12d3cc9b8
spring.mail.password=996c75ac797094
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ??? reCAPTCHA ????????????????????????????????????????????????????
recaptcha.secret=6Lfl56gsAAAAANBX5wlGVQdY77k-gOkTxPzWfmyw
recaptcha.url=https://www.google.com/recaptcha/api/siteverify

# ??? JWT ??????????????????????????????????????????????????????????
# ??????? 32 ???????! ???? ????? ?????????? ?? ???? ???????
jwt.secret=nti-super-secret-key-minimum-32-chars-change-in-prod!!
# 24 ?????? ? ????????????
jwt.expiration-ms=86400000

# ??? URL ??????? ??????????????????????????????????????????????????
app.backend-url=http://localhost:8080
app.frontend-url=http://localhost:5173

# ??? Email ?????? ?????????????????????????????????????????????????
app.mail.from=noreply@nti.sk
app.mail.admin=admin@nti.sk