CREATE TABLE programs
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    type        VARCHAR(255)                            NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_programs PRIMARY KEY (id)
);